import React, { useState } from 'react';
import { motion } from 'framer-motion';
import CalendarTodayIcon from '@mui/icons-material/CalendarToday';
import QuizIcon from '@mui/icons-material/Quiz';
import ForumIcon from '@mui/icons-material/Forum';
import NoteIcon from '@mui/icons-material/Note';

function FeaturesSection() {
  const [expanded, setExpanded] = useState(null);

  const features = [
    {
      name: 'Study Planner',
      image: 'https://m.media-amazon.com/images/I/519Rj0uihYL.jpg',
      description: 'Create personalized study plans with deadlines and topic tracking. Stay organized and get reminders to keep you on track.',
      fullDescription: 'Our Study Planner lets you input your field, subjects, deadlines, and topics to create a tailored schedule. Mark topics as done, receive timely reminders, and visualize your progress with an intuitive timeline.',
      icon: <CalendarTodayIcon className="text-teal-400" />,
    },
    {
      name: 'Interactive Quizzes',
      image: 'https://static.vecteezy.com/system/resources/previews/059/912/877/non_2x/quiz-neon-sign-with-brick-wall-background-free-vector.jpg',
      description: 'Test your knowledge with AI-generated quizzes tailored to your subjects and difficulty level.',
      fullDescription: 'Engage with dynamic quizzes generated by AI, covering your chosen topics. Get instant feedback and a revision sheet for topics you need to review.',
      icon: <QuizIcon className="text-teal-400" />,
    },
    {
      name: 'Conversation Forum',
      image: 'https://cdn.prod.website-files.com/651286e75f334691f08e3fd1/66e91a060a905073342c8ef1_1.webp',
      description: 'Connect with peers, ask questions, and share knowledge in our community forum.',
      fullDescription: 'Our forum offers two sections: a Q&A area for academic queries and a chat section for casual discussions. Collaborate and learn from others in real-time.',
      icon: <ForumIcon className="text-teal-400" />,
    },
    {
      name: 'My Notes',
      image: 'https://plus.unsplash.com/premium_photo-1705178701080-1e0eae873f7e?q=80&w=1288&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      description: 'Create, edit, and organize your study notes in one place.',
      fullDescription: 'Easily jot down notes, edit them, or delete them as needed. Organize your thoughts and access them anytime to support your learning journey.',
      icon: <NoteIcon className="text-teal-400" />,
    },
    {
        name: 'Games',
        image: 'https://i.ytimg.com/vi/hVJaz9CM1ok/maxresdefault.jpg',
        description: 'Are you bore? Invite your friends and play exciting study game to have fun and boost your knowledge.',
        fullDescription: 'Easily jot down notes, edit them, or delete them as needed. Organize your thoughts and access them anytime to support your learning journey.',
        icon: <NoteIcon className="text-teal-400" />,
      },
  ];

  return (
    <section className="py-12 bg-gray-900 text-gray-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.h2
          className="text-3xl font-bold text-teal-400 mb-8 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          Our Features
        </motion.h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              className="bg-gradient-dark p-6 rounded-lg shadow-lg hover:shadow-2xl transition-all duration-300 border border-gray-800"
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              whileHover={{ scale: 1.05 }}
              viewport={{ once: true }}
            >
              <img src={feature.image} alt={feature.name} className="w-full h-40 object-cover rounded-md mb-4" />
              <div className="flex items-center mb-2">
                {feature.icon}
                <h3 className="text-xl font-semibold ml-2 text-purple-400">{feature.name}</h3>
              </div>
              <p className="text-gray-200">
                {expanded === index ? feature.fullDescription : feature.description}
              </p>
              <motion.button
                className="text-teal-400 hover:text-pink-500 mt-2"
                onClick={() => setExpanded(expanded === index ? null : index)}
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
              >
                {expanded === index ? 'Show Less' : 'Read More'}
              </motion.button>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default FeaturesSection;